pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage("Build") {
            steps {
                sh "mvn -f abc-dmeoservice/pom.xml clean install"
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
    }
}