pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage("Build")
        {
	        withMaven(maven: 'mvn') {
	            sh "mvn clean install"
	        }
    	}
    	
        stage("Build")
        {
	        withMaven(maven: 'mvn') {
	            sh "mvn clean install"
	        }
    	}
    }
}