
pipeline {
    agent any
    tools { 
        maven 'M3' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('Build Maven') {
            steps {
            	sh "mvn -f abc-demoservice/pom.xml clean install"
                echo 'This is a minimal pipeline.'
            }
        }
        
        stage ('Docker Build')
        {
            steps {
            
            
            		  sh "pwd"
                   
                       sh "docker build -t mkhalid003/abc-demoservice ."
                                                
                  }
          }
          
          
        stage ('Docker Push to Docker Hub') 
        {
            steps {
            
            		sh "docker login -u mkhalid003 -p Welcome@99 http://hub.docker.com" 
                          
                    sh "docker push mkhalid003/abc-demoservice ."  
                                            
            	}
        }
        
      
        
    }
}